<?php require('template/header.phtml') ?>
<h1>This is the Home Page.</h1>

<p>This site is designed using the <a href="http://www.960.gs">960gs CSS framework</a>.</p>
<p><a href="http://www.rickogden.com/tutorials/960gs/">Click here for a tutorial.</a></p>
<p>This template (written by Rick Cooper) uses the 960gs CSS framework to design the site structure.</p>
<p>In the Views/template directory it contains a header.phtml and a footer.phtml which are included on every new page generated. To add additional pages just edit the file header.phtml to add the extra link and then add a new controller (pagex.php) and a new view (pagex.phtml) for each page required.</p>
<?php require('template/footer.phtml') ?>
