<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <title><?php echo $view->pageTitle; ?></title>
        <link href="css/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="css/css/960.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="css/css/text.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="css/style.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="container" class="container_16">
            <div id="title" class="grid_16">
                <header>
                    Game Test
                </header>
            </div>
        <div id="container" class="container_16">
            <div id="menu" class="grid_3">
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="blackjack.php">Blackjack</a></li>
                </ul>
            </div>
            <div id="content" class="grid_13">
